### ISSUE TITLE
Let me join to your organization!

### ISSUE THREAD

**Issue by thuongtruong1009** [mkschulze/GraknClient.jl#126]
Hi there!
My name is Tran Nguyen Thuong Truong - @thuongtruong1009
Currently, I learning front-end.
I want to learn more and more about open-source code.
Hope to cooperate with you in the future.
Thank you!

**Comment by mkschulze** [comment]
Sent you an invitation. Would be nice if you could join our Discord, so we get to know you. That way we can also update you with information about the current state and plans.

https://discord.gg/C5h9D4j

Welcome!
Mark

**Comment by mkschulze** [comment]
https://discord.gg/C5h9D4j

**Comment by thuongtruong1009** [comment]
yes, I have just joined discord serve.
Thank you!
